"""add_widget_tracking_fields

Revision ID: 014e47c1d737
Revises: 3668fee50ee2
Create Date: 2026-02-07 21:58:57.401643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014e47c1d737'
down_revision: Union[str, Sequence[str], None] = '3668fee50ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('allowed_domains', sa.JSON(), nullable=True))
    op.add_column('conversations', sa.Column('referrer_url', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('page_title', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('hostname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'hostname')
    op.drop_column('conversations', 'page_title')
    op.drop_column('conversations', 'referrer_url')
    op.drop_column('agents', 'allowed_domains')
    # ### end Alembic commands ###
