"""add_stripe_billing_fields

Revision ID: 03b18c53669b
Revises: f7a2c3d4e5b6
Create Date: 2026-03-21 15:00:10.611929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b18c53669b'
down_revision: Union[str, Sequence[str], None] = 'f7a2c3d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('workspaces', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'current_period_end')
    op.drop_column('workspaces', 'stripe_subscription_id')
    op.drop_column('workspaces', 'stripe_customer_id')
    # ### end Alembic commands ###
