"""Add language field to workspace



Revision ID: 0be00c6626cb
Revises: c8f4e5a2b3d1
Create Date: 2026-01-25 22:35:38.208978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0be00c6626cb'
down_revision: Union[str, Sequence[str], None] = 'c8f4e5a2b3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_embeddings_embedding'), table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('otps', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_otps_email_purpose'), table_name='otps')
    op.add_column('workspaces', sa.Column('language', sa.String(length=10), nullable=False))
    op.alter_column('workspaces', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.alter_column('workspaces', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('workspaces', 'language')
    op.create_index(op.f('ix_otps_email_purpose'), 'otps', ['email', 'purpose'], unique=False)
    op.alter_column('otps', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_embeddings_embedding'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
