"""update_embedding_dimension_384

Revision ID: 3668fee50ee2
Revises: 278fb967597d
Create Date: 2026-02-04 20:55:56.410824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3668fee50ee2'
down_revision: Union[str, Sequence[str], None] = '278fb967597d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE embeddings ALTER COLUMN embedding TYPE vector(384);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
