"""add_ai_model

Revision ID: 46b58f2b2baa
Revises: 03b18c53669b
Create Date: 2026-03-21 15:06:21.907476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b58f2b2baa'
down_revision: Union[str, Sequence[str], None] = '03b18c53669b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('ai_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'ai_model')
    # ### end Alembic commands ###
